// <auto-generated />
using System;
using LibraryAppWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryAppWebAPI.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("LibraryAppWebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("RackId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.K. Rowling",
                            Genre = "FANTASY",
                            ISBN = "9781856134033",
                            PublicationDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Bloomsbury",
                            RackId = 1,
                            Title = "Harry Potter and The Philosopher's Stone"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            Genre = "FANTASY",
                            ISBN = "9780261103573",
                            PublicationDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "George Allen & Unwin",
                            RackId = 2,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Genre = "FICTION",
                            ISBN = "9780451524935",
                            PublicationDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Secker & Warburg",
                            RackId = 2,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Harper Lee",
                            Genre = "FICTION",
                            ISBN = "9780061120084",
                            PublicationDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "J.B. Lippincott & Co.",
                            RackId = 2,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Mary Shelley",
                            Genre = "HORROR",
                            ISBN = "9780141439471",
                            PublicationDate = new DateTime(1818, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Lackington, Hughes, Harding, Mavor & Jones",
                            RackId = 5,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Isaac Asimov",
                            Genre = "SCIENCE_FICTION",
                            ISBN = "9780553293357",
                            PublicationDate = new DateTime(1951, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Gnome Press",
                            RackId = 5,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Douglas Adams",
                            Genre = "SCIENCE_FICTION",
                            ISBN = "9780345391803",
                            PublicationDate = new DateTime(1979, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Pan Books",
                            RackId = 2,
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Leo Tolstoy",
                            Genre = "FICTION",
                            ISBN = "9780199232765",
                            PublicationDate = new DateTime(1869, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "The Russian Messenger",
                            RackId = 3,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Mark Twain",
                            Genre = "FICTION",
                            ISBN = "9780486280615",
                            PublicationDate = new DateTime(1884, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Chatto & Windus",
                            RackId = 3,
                            Title = "Adventures of Huckleberry Finn"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Jane Austen",
                            Genre = "ROMANCE",
                            ISBN = "9780141439518",
                            PublicationDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "T. Egerton",
                            RackId = 3,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Ernest Hemingway",
                            Genre = "FICTION",
                            ISBN = "9780684801223",
                            PublicationDate = new DateTime(1952, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Charles Scribner's Sons",
                            RackId = 3,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Agatha Christie",
                            Genre = "MYSTERY",
                            ISBN = "9780007119356",
                            PublicationDate = new DateTime(1934, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Collins Crime Club",
                            RackId = 4,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Dan Brown",
                            Genre = "THRILLER",
                            ISBN = "9780385504201",
                            PublicationDate = new DateTime(2003, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Doubleday",
                            RackId = 4,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Stephen King",
                            Genre = "HORROR",
                            ISBN = "9780451169525",
                            PublicationDate = new DateTime(1977, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Doubleday",
                            RackId = 5,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Suzanne Collins",
                            Genre = "YOUNG_ADULT",
                            ISBN = "9780439023481",
                            PublicationDate = new DateTime(2008, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scholastic Press",
                            RackId = 1,
                            Title = "The Hunger Games"
                        },
                        new
                        {
                            Id = 16,
                            Author = "C.S. Lewis",
                            Genre = "FANTASY",
                            ISBN = "9780064471190",
                            PublicationDate = new DateTime(1950, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Geoffrey Bles",
                            RackId = 1,
                            Title = "The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Id = 17,
                            Author = "H.G. Wells",
                            Genre = "SCIENCE_FICTION",
                            ISBN = "9780553213515",
                            PublicationDate = new DateTime(1895, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "William Heinemann",
                            RackId = 5,
                            Title = "The Time Machine"
                        },
                        new
                        {
                            Id = 18,
                            Author = "John Steinbeck",
                            Genre = "FICTION",
                            ISBN = "9780140177398",
                            PublicationDate = new DateTime(1937, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Covici Friede",
                            RackId = 3,
                            Title = "Of Mice and Men"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Arthur Conan Doyle",
                            Genre = "MYSTERY",
                            ISBN = "9780451528019",
                            PublicationDate = new DateTime(1892, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "George Newnes",
                            RackId = 4,
                            Title = "The Adventures of Sherlock Holmes"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Ray Bradbury",
                            Genre = "SCIENCE_FICTION",
                            ISBN = "9781451673319",
                            PublicationDate = new DateTime(1953, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Ballantine Books",
                            RackId = 5,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 21,
                            Author = "William Golding",
                            Genre = "FICTION",
                            ISBN = "9780399501487",
                            PublicationDate = new DateTime(1954, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Faber and Faber",
                            RackId = 2,
                            Title = "Lord of the Flies"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Charles Dickens",
                            Genre = "FICTION",
                            ISBN = "9780141439600",
                            PublicationDate = new DateTime(1861, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Chapman & Hall",
                            RackId = 3,
                            Title = "Great Expectations"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Emily Brontë",
                            Genre = "ROMANCE",
                            ISBN = "9780141439556",
                            PublicationDate = new DateTime(1847, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Thomas Cautley Newby",
                            RackId = 3,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Homer",
                            Genre = "HISTORY",
                            ISBN = "9780140268867",
                            PublicationDate = new DateTime(1500, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Ancient Greece",
                            RackId = 3,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Victor Hugo",
                            Genre = "FICTION",
                            ISBN = "9780451419430",
                            PublicationDate = new DateTime(1862, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "A. Lacroix, Verboeckhoven & Cie.",
                            RackId = 3,
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Bram Stoker",
                            Genre = "HORROR",
                            ISBN = "9780486411095",
                            PublicationDate = new DateTime(1897, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Archibald Constable and Company",
                            RackId = 5,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Aldous Huxley",
                            Genre = "SCIENCE_FICTION",
                            ISBN = "9780060850524",
                            PublicationDate = new DateTime(1932, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Chatto & Windus",
                            RackId = 2,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Jules Verne",
                            Genre = "SCIENCE_FICTION",
                            ISBN = "9780553213973",
                            PublicationDate = new DateTime(1870, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Pierre-Jules Hetzel",
                            RackId = 5,
                            Title = "Twenty Thousand Leagues Under the Seas"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Miguel de Cervantes",
                            Genre = "FICTION",
                            ISBN = "9780060934347",
                            PublicationDate = new DateTime(1605, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Francisco de Robles",
                            RackId = 3,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 30,
                            Author = "George R.R. Martin",
                            Genre = "FANTASY",
                            ISBN = "9780553103540",
                            PublicationDate = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Bantam Spectra",
                            RackId = 2,
                            Title = "A Game of Thrones"
                        });
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.BorrowingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowingRecords");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MembershipDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@gmail.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "One",
                            Password = "Pass123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@gmail.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Two",
                            Password = "Pass123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@gmail.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Three",
                            Password = "Pass123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@gmail.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Four",
                            Password = "Pass123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@gmail.com",
                            IsActive = true,
                            MembershipDate = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MembershipId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Five",
                            Password = "Pass123"
                        });
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Rack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Racks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            Floor = 1,
                            Section = "CHILDREN"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            Floor = 1,
                            Section = "FICTION"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Floor = 2,
                            Section = "NONFICTION"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            Floor = 2,
                            Section = "REFERENCE"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 20,
                            Floor = 3,
                            Section = "SCIENCE"
                        });
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Book", b =>
                {
                    b.HasOne("LibraryAppWebAPI.Models.Rack", "Rack")
                        .WithMany("Books")
                        .HasForeignKey("RackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.BorrowingRecord", b =>
                {
                    b.HasOne("LibraryAppWebAPI.Models.Book", "Book")
                        .WithMany("BorrowingHistory")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryAppWebAPI.Models.Member", "Member")
                        .WithMany("BorrowingHistory")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Book", b =>
                {
                    b.Navigation("BorrowingHistory");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Member", b =>
                {
                    b.Navigation("BorrowingHistory");
                });

            modelBuilder.Entity("LibraryAppWebAPI.Models.Rack", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
